"use client";
import { useState } from "react";
import { FileSpreadsheet, Printer } from "lucide-react";
import { Badge, Button, Card, EmptyState, PageHeader, SectionHeader, Tabs } from "@/components/ui";
import { createReportExportModel } from "@/lib/report-export";
import { formatMinutes } from "@/lib/format";
import { useDemo } from "@/state/DemoContext";
import type { ReportPeriod } from "@/lib/report-query";

export function RealAdminReportsView() {
  const { getReport, pushToast } = useDemo();
  const [period, setPeriod] = useState<ReportPeriod>("weekly");
  const report = getReport({ period, participantId: "all", taskId: "all" });
  const exportCurrent = async () => { if (!report.hasData) return; const { exportXlsxReport } = await import("@/lib/xlsx-export"); await exportXlsxReport(createReportExportModel(report), `group-report-${period}`); pushToast({ tone: "success", title: "تم تصدير تقرير المجموعة", body: "يتضمن الملف الملخص والأيام والمهام والمشاركين." }); };
  return <div dir="rtl" className="admin-report-page"><PageHeader eyebrow="متابعة المجموعة" title="تقارير الأداء" description="تجميع فعلي حسب الفترة، بدون بيانات تجريبية." actions={<div className="admin-report-actions"><Button size="sm" variant="outline" onClick={() => window.print()}><Printer size={16} />طباعة</Button><Button size="sm" disabled={!report.hasData} onClick={exportCurrent}><FileSpreadsheet size={16} />تصدير Excel</Button></div>} /><Tabs value={period} onValueChange={setPeriod} tabs={[{ value: "daily", label: "يومي" }, { value: "weekly", label: "أسبوعي" }, { value: "monthly", label: "شهري" }]} /><Card><SectionHeader title="نطاق التقرير" description={`${report.dateRange.start} — ${report.dateRange.end}`} /><div className="admin-report-kpis"><div><small>متوسط الإنجاز</small><strong>{report.hasData ? `${report.completionRate}%` : "—"}</strong></div><div><small>وقت المجموعة الفعلي</small><strong>{report.hasData ? formatMinutes(report.totalMinutes) : "—"}</strong></div><div><small>أيام نجاح مسجلة</small><strong>{report.hasData ? report.successfulDays : "—"}</strong></div><div><small>أعلى إنجاز في الفترة</small><strong>{report.topParticipant ?? "—"}</strong></div></div></Card><Card><SectionHeader title="المشاركون" description="كل صف محسوب من سجلات المشارك داخل الفترة نفسها." />{report.participantRows.length ? <div className="admin-report-participants">{report.participantRows.map((row) => <article key={row.participantId}><strong>{row.name}</strong><span>{row.completionRate}% إنجاز · {row.successfulDays} أيام نجاح · {formatMinutes(row.actualMinutes)}</span><Badge tone={row.completionRate >= 90 ? "success" : "neutral"}>{row.completionRate}%</Badge></article>)}</div> : <EmptyState title="لا توجد بيانات مسجلة لهذه الفترة" description="لن يتم إنشاء نشاط تجريبي أو تصدير فارغ." />}</Card><Card><SectionHeader title="أداء المهام" />{report.taskRows.length ? <div className="report-task-list">{report.taskRows.map((row) => <article key={row.taskId}><div><strong>{row.title}</strong><span>{row.completionRate}% إنجاز · {row.completed} مكتملة · {row.partial} جزئية</span></div><strong>{formatMinutes(row.actualMinutes)}</strong></article>)}</div> : <EmptyState title="لا توجد مهام مسجلة" />}</Card></div>;
}
