// البيانات الأولية الواقعية المتطابقة مع قاعدة بيانات رحلة التغيير
import type { Participant, TaskCategory, TaskItem, ActivityEvent, BadgeItem } from '../types';

export const INITIAL_CATEGORIES: TaskCategory[] = [
  { id: 'cat-1', slug: 'deen', nameAr: 'دين', icon: '🕌', color: '#059669', bgGradient: 'from-emerald-500/20 to-teal-500/10' },
  { id: 'cat-2', slug: 'culture', nameAr: 'ثقافة', icon: '📚', color: '#2563EB', bgGradient: 'from-blue-500/20 to-indigo-500/10' },
  { id: 'cat-3', slug: 'sport', nameAr: 'رياضة', icon: '⚽', color: '#EA580C', bgGradient: 'from-orange-500/20 to-amber-500/10' },
  { id: 'cat-4', slug: 'self-development', nameAr: 'تطوير الذات', icon: '🎯', color: '#7C3AED', bgGradient: 'from-purple-500/20 to-violet-500/10' },
  { id: 'cat-5', slug: 'skill', nameAr: 'مهارة', icon: '🛠️', color: '#0891B2', bgGradient: 'from-cyan-500/20 to-teal-500/10' },
  { id: 'cat-6', slug: 'life', nameAr: 'حياة', icon: '🌟', color: '#EAB308', bgGradient: 'from-yellow-500/20 to-amber-500/10' },
  { id: 'cat-7', slug: 'family', nameAr: 'أهل وبيت', icon: '👨‍👩‍👧‍👦', color: '#DB2777', bgGradient: 'from-pink-500/20 to-rose-500/10' },
  { id: 'cat-8', slug: 'health', nameAr: 'صحة', icon: '💪', color: '#0D9488', bgGradient: 'from-teal-500/20 to-emerald-500/10' },
  { id: 'cat-9', slug: 'ethics', nameAr: 'أخلاق', icon: '💎', color: '#4F46E5', bgGradient: 'from-indigo-500/20 to-purple-500/10' },
];

export const INITIAL_PARTICIPANTS: Participant[] = [
  {
    id: 'user-1',
    displayName: 'عبدالله محمود',
    role: 'ADMIN',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    pin: '1234',
    rankTitle: 'حارس الزمرد 🛡️',
    jobTitle: 'مهندس برمجيات ورائد التغيير',
    presence: 'WORKING',
    lastSeenAt: 'الآن',
    currentStreakDays: 14,
    isStreakAtRisk: false,
    totalPoints: 1450,
    todayPoints: 85,
    isActive: true,
  },
  {
    id: 'user-2',
    displayName: 'ريم العتيبي',
    role: 'PARTICIPANT',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    pin: '1234',
    rankTitle: 'رائدة تطوير العادات 👑',
    jobTitle: 'مصممة واجهات ومبتكرة',
    presence: 'WORKING',
    lastSeenAt: 'الآن',
    currentStreakDays: 19,
    isStreakAtRisk: false,
    totalPoints: 1890,
    todayPoints: 95,
    isActive: true,
  },
  {
    id: 'user-3',
    displayName: 'رازي أحمد',
    role: 'PARTICIPANT',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    pin: '1234',
    rankTitle: 'رفيق القرآن 📖',
    jobTitle: 'باحث وطالب علم',
    presence: 'ONLINE',
    lastSeenAt: 'منذ 3 دقائق',
    currentStreakDays: 12,
    isStreakAtRisk: false,
    totalPoints: 1240,
    todayPoints: 70,
    isActive: true,
  },
  {
    id: 'user-4',
    displayName: 'سامي الجابر',
    role: 'PARTICIPANT',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    pin: '1234',
    rankTitle: 'سيد الاستمرارية ⚡',
    jobTitle: 'رائد أعمال',
    presence: 'PAUSED',
    lastSeenAt: 'منذ 10 دقائق',
    currentStreakDays: 8,
    isStreakAtRisk: false,
    totalPoints: 980,
    todayPoints: 50,
    isActive: true,
  },
  {
    id: 'user-5',
    displayName: 'زياد الحربي',
    role: 'PARTICIPANT',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    pin: '1234',
    rankTitle: 'فارس الانطلاق 🚀',
    jobTitle: 'محلل بيانات',
    presence: 'IDLE',
    lastSeenAt: 'منذ ساعتين',
    currentStreakDays: 4,
    isStreakAtRisk: true, // الستريك في خطر!
    totalPoints: 410,
    todayPoints: 10,
    isActive: true,
  },
];

export const INITIAL_TASKS: TaskItem[] = [
  {
    id: 'task-1',
    categoryId: 'deen',
    typeCode: 'PRAYER',
    title: 'الصلوات الخمس المكتوبة',
    subtitle: 'المحافظة على الصلاة في وقتها بخشوع وسكينة',
    fullPoints: 25,
    partialPoints: 12.5,
    earnedPoints: 25,
    status: 'COMPLETED_FULL',
    elapsedSeconds: 1800,
    isTimerRunning: false,
    meta: {
      prayersCompleted: ['FAJR', 'DHUHR', 'ASR'],
    },
  },
  {
    id: 'task-2',
    categoryId: 'deen',
    typeCode: 'QURAN',
    title: 'ورد القرآن الكريم وتأمل اليوم',
    subtitle: 'قراءة نصف جزء مع تدبر وتأمل الآيات',
    fullPoints: 20,
    partialPoints: 10,
    earnedPoints: 20,
    status: 'COMPLETED_FULL',
    elapsedSeconds: 1520,
    isTimerRunning: false,
    meta: {
      quranSurah: 'سورة الكهف',
      quranAyah: 28,
      tafsirSummary: '«وَاصْبِرْ نَفْسَكَ مَعَ الَّذِينَ يَدْعُونَ رَبَّهُم بِالْغَدَاةِ وَالْعَشِيِّ يُرِيدُونَ وَجْهَهُ» — دليل واضح على أثر الصحبة الصالحة والاستمرارية في الطاعات.',
    },
  },
  {
    id: 'task-3',
    categoryId: 'culture',
    typeCode: 'READING',
    title: 'قراءة كتاب الأسبوع',
    subtitle: 'كتاب: العادات الذرية (Atomic Habits) - جيمس كلير',
    fullPoints: 15,
    partialPoints: 7.5,
    earnedPoints: 0,
    status: 'IN_PROGRESS',
    elapsedSeconds: 940,
    isTimerRunning: true, // المهمة الحالية النشطة!
    meta: {
      bookTitle: 'العادات الذرية - Atomic Habits',
      targetPages: 20,
      currentPages: 14,
    },
  },
  {
    id: 'task-4',
    categoryId: 'sport',
    typeCode: 'SPORT',
    title: 'النشاط الرياضي واللياقة',
    subtitle: 'حرية الحركة: مشي سريع أو تمارين كارديو',
    fullPoints: 15,
    partialPoints: 7.5,
    earnedPoints: 0,
    status: 'NOT_STARTED',
    elapsedSeconds: 0,
    isTimerRunning: false,
    meta: {
      sportActivity: 'مشي نشط في الهواء الطلق',
      targetDurationMinutes: 30,
    },
  },
  {
    id: 'task-5',
    categoryId: 'health',
    typeCode: 'WATER',
    title: 'الارتواء وشرب الماء',
    subtitle: 'الهدف اليومي: 2.5 لتر (10 كؤوس نقية)',
    fullPoints: 10,
    partialPoints: 5,
    earnedPoints: 5,
    status: 'COMPLETED_PARTIAL',
    elapsedSeconds: 0,
    isTimerRunning: false,
    meta: {
      targetWaterCups: 10,
      currentWaterCups: 6,
    },
  },
  {
    id: 'task-6',
    categoryId: 'health',
    typeCode: 'SLEEP',
    title: 'النوم الصحي والاستيقاظ المبكر',
    subtitle: 'ساعات النوم الهادئ وأذكار الصباح المباركة',
    fullPoints: 10,
    partialPoints: 5,
    earnedPoints: 10,
    status: 'COMPLETED_FULL',
    elapsedSeconds: 0,
    isTimerRunning: false,
    meta: {
      sleepHours: 7.5,
    },
  },
  {
    id: 'task-7',
    categoryId: 'life',
    typeCode: 'MEDITATION',
    title: 'جلسة التأمل والاسترخاء الروحي',
    subtitle: 'تفريغ ذهني وتنفس متزن وذكر وتسبيح',
    fullPoints: 10,
    partialPoints: 5,
    earnedPoints: 0,
    status: 'NOT_STARTED',
    elapsedSeconds: 0,
    isTimerRunning: false,
    meta: {
      targetDurationMinutes: 10,
    },
  },
];

export const INITIAL_ACTIVITIES: ActivityEvent[] = [
  {
    id: 'act-1',
    participantId: 'user-1',
    participantName: 'عبدالله محمود',
    participantAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    type: 'STARTED',
    taskTitle: 'قراءة كتاب الأسبوع',
    categorySlug: 'culture',
    timestamp: new Date().toISOString(),
    timeFormatted: 'منذ دقيقة',
  },
  {
    id: 'act-2',
    participantId: 'user-3',
    participantName: 'رازي أحمد',
    participantAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    type: 'FINISHED_FULL',
    taskTitle: 'ورد القرآن الكريم وتأمل اليوم',
    categorySlug: 'deen',
    timestamp: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    timeFormatted: '8:44 م',
  },
  {
    id: 'act-3',
    participantId: 'user-4',
    participantName: 'سامي الجابر',
    participantAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    type: 'PAUSED',
    taskTitle: 'النشاط الرياضي واللياقة',
    categorySlug: 'sport',
    timestamp: new Date(Date.now() - 14 * 60 * 1000).toISOString(),
    timeFormatted: '8:30 م',
  },
  {
    id: 'act-4',
    participantId: 'user-2',
    participantName: 'ريم العتيبي',
    participantAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    type: 'CHEER',
    timestamp: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    timeFormatted: '8:15 م',
    cheerMessage: 'أرسلت تشجيعاً حماسياً لزياد الحربي: «شد حيلك يا بطل، خطوة واحدة وتحمي الستريك! 🔥»',
  },
];

export const INITIAL_BADGES: BadgeItem[] = [
  { id: 'b-1', title: 'حارس الزمرد', description: 'الوصول إلى 14 يوماً متواصلاً بنسبة إنجاز تفوق 90%', icon: '🛡️', tier: 'EMERALD', isUnlocked: true, unlockedAt: 'أمس' },
  { id: 'b-2', title: 'رفيق القرآن', description: 'المحافظة على ورد التلاوة والتأمل لمدة 7 أيام متتالية', icon: '📖', tier: 'GOLD', isUnlocked: true, unlockedAt: 'منذ 3 أيام' },
  { id: 'b-3', title: 'سيد الاستمرارية', description: 'إنهاء جميع مهام اليوم قبل موعد المساء', icon: '⚡', tier: 'GOLD', isUnlocked: true, unlockedAt: 'منذ أسبوع' },
  { id: 'b-4', title: 'ينبوع الصحة', description: 'إتمام شرب 10 كؤوس ماء لمدة 5 أيام متتالية', icon: '💧', tier: 'SILVER', isUnlocked: true, unlockedAt: 'منذ أسبوعين' },
  { id: 'b-5', title: 'فارس الفجر', description: 'أداء صلاة الفجر وتسجيل أذكار الصباح قبل شروق الشمس', icon: '🌅', tier: 'GOLD', isUnlocked: true, unlockedAt: 'اليوم' },
  { id: 'b-6', title: 'العقل المتوقد', description: 'قراءة 100 صفحة وإتمام تلخيصين للكتب', icon: '🧠', tier: 'EMERALD', isUnlocked: false },
];
