import type { ReportDataset, ReportPeriod } from "./report-query.ts";

export interface ReportExportModel { summary: Array<Record<string, string | number>>; timeline: Array<Record<string, string | number>>; tasks: Array<Record<string, string | number>>; participants?: Array<Record<string, string | number>>; }
const periodLabel: Record<ReportPeriod, string> = { daily: "يومي", weekly: "أسبوعي", monthly: "شهري" };
export function createReportExportModel(report: ReportDataset): ReportExportModel {
  const scope = report.filters.participantId === "all" ? "كل المشاركين" : report.participantRows[0]?.name ?? "مشارك محدد";
  return { summary: [{ "نوع التقرير": periodLabel[report.filters.period], "نطاق التاريخ": `${report.dateRange.start} — ${report.dateRange.end}`, "المشارك": scope, "المهمة": report.filters.taskId === "all" ? "كل المهام" : report.taskRows[0]?.title ?? "مهمة محددة", "نسبة الإنجاز": report.completionRate, "إجمالي الوقت الفعلي بالدقائق": report.totalMinutes, "أيام النجاح": report.successfulDays, "الأسابيع الناجحة": report.successfulWeeks, [report.filters.participantId === "all" ? "حالات يوم مسجلة" : "أيام مسجلة"]: report.recordedDays, "متوسط الدقائق اليومية": report.averageDailyMinutes, "أكثر مهمة استهلاكًا للوقت": report.mostTimeConsumingTask ?? "—", ...(report.filters.participantId === "all" ? { "أعلى مشارك": report.topParticipant ?? "—" } : {}) }], timeline: report.points.map((point) => ({ "الفترة": point.label, "نسبة الإنجاز": point.hasData ? point.progress : "—", "الوقت الفعلي بالدقائق": point.minutes, "حالة البيانات": point.hasData ? "مسجلة" : "غير مسجلة" })), tasks: report.taskRows.map((row) => ({ "المهمة": row.title, "نسبة الإنجاز": row.completionRate, "الوقت الفعلي بالدقائق": row.actualMinutes, "مكتملة": row.completed, "جزئية": row.partial, "لم تُنجز": row.notCompleted, "مغلقة": row.closed })), ...(report.filters.participantId === "all" ? { participants: report.participantRows.map((row) => ({ "المشارك": row.name, "نسبة الإنجاز": row.completionRate, "أيام النجاح": row.successfulDays, "الوقت الفعلي بالدقائق": row.actualMinutes })) } : {}) };
}
export function reportExportSheets(model: ReportExportModel) { return { "الملخص": model.summary, "الأيام": model.timeline, "المهام": model.tasks, ...(model.participants ? { "المشاركون": model.participants } : {}) }; }
